2023-04-13 17:16:22,594 INFO root Token successfully initted: 6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c
2023-04-13 17:16:22,595 INFO root Bot successfully initted
2023-04-13 17:16:22,595 INFO root DB connected successfully, cursor created
2023-04-13 17:16:22,599 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:16:22,901 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getMe HTTP/1.1" 200 191
2023-04-13 17:16:22,908 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:16:30,067 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 398
2023-04-13 17:16:30,072 ERROR TeleBot Infinity polling exception: name 'markup_inline' is not defined
2023-04-13 17:16:30,073 ERROR TeleBot Exception traceback:
Traceback (most recent call last):
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\favanek\main.py", line 84, in suggest_message
    reply_markup=markup_inline)
NameError: name 'markup_inline' is not defined

2023-04-13 17:16:33,089 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:16:33,426 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040607&timeout=20 HTTP/1.1" 409 143
2023-04-13 17:16:53,426 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040607&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:17:13,526 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040607&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:17:28,553 ERROR TeleBot Infinity polling: polling exited
2023-04-13 17:17:28,554 ERROR TeleBot Break infinity polling
2023-04-13 17:17:28,554 INFO root Bot STOPPED
