2023-04-13 17:19:40,517 INFO root Token successfully initted: 6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c
2023-04-13 17:19:40,518 INFO root Bot successfully initted
2023-04-13 17:19:40,518 INFO root DB connected successfully, cursor created
2023-04-13 17:19:40,522 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:19:40,828 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getMe HTTP/1.1" 200 191
2023-04-13 17:19:40,832 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:19:45,775 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 398
2023-04-13 17:19:45,782 ERROR TeleBot Infinity polling exception: name 'call' is not defined
2023-04-13 17:19:45,784 ERROR TeleBot Exception traceback:
Traceback (most recent call last):
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\favanek\main.py", line 84, in suggest_message
    cancel_button = types.InlineKeyboardButton(call.id, text='ќтмена')
NameError: name 'call' is not defined

2023-04-13 17:19:48,800 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:19:49,068 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 409 143
2023-04-13 17:20:09,061 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:20:29,169 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:20:49,251 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:21:09,462 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:21:29,547 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:21:49,623 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:22:09,701 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:22:29,779 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:22:49,865 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:23:09,949 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:23:30,033 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:23:50,122 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:24:10,201 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:24:30,284 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:24:50,364 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:25:10,442 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040609&timeout=20 HTTP/1.1" 200 23
