2023-04-13 17:35:55,763 INFO root Token successfully initted: 6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c
2023-04-13 17:35:55,764 INFO root Bot successfully initted
2023-04-13 17:35:55,765 INFO root DB connected successfully, cursor created
2023-04-13 17:35:55,768 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:35:56,266 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getMe HTTP/1.1" 200 191
2023-04-13 17:35:56,275 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:36:01,768 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 398
2023-04-13 17:36:01,774 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:36:02,113 DEBUG urllib3.connectionpool https://api.telegram.org:443 "POST /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/sendMessage?chat_id=1515397583&text=%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%B2%D0%B2%D0%B5%D0%B4%D0%B8%D1%82%D0%B5+%D0%92%D0%B0%D1%88+%D0%B0%D0%BD%D0%B5%D0%BA%D0%B4%D0%BE%D1%82.+%D0%95%D1%81%D0%BB%D0%B8+%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D1%83%D0%BC%D0%B0%D0%BB%D0%B8+-+%2Fcancel+%D0%B2+%D0%BF%D0%BE%D0%BC%D0%BE%D1%89%D1%8C&reply_markup=%7B%22inline_keyboard%22%3A+%5B%5B%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu043c%5Cu0435%5Cu043d%5Cu0430%22%2C+%22callback_data%22%3A+%22%2Fcancel%22%7D%5D%5D%7D HTTP/1.1" 200 738
2023-04-13 17:36:03,988 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040615&timeout=20 HTTP/1.1" 200 997
2023-04-13 17:36:04,000 ERROR TeleBot Infinity polling exception: 'CallbackQuery' object has no attribute 'chat'
2023-04-13 17:36:04,001 ERROR TeleBot Exception traceback:
Traceback (most recent call last):
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\favanek\main.py", line 94, in callback_inline
    bot.send_message(message.chat.id, '¬озвращайтесь, как передумаете ;)')
AttributeError: 'CallbackQuery' object has no attribute 'chat'

2023-04-13 17:36:05,276 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040616&timeout=20 HTTP/1.1" 200 997
2023-04-13 17:36:07,009 ERROR TeleBot Infinity polling exception: 'CallbackQuery' object has no attribute 'chat'
2023-04-13 17:36:07,011 ERROR TeleBot Exception traceback:
Traceback (most recent call last):
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\яндекс 2 год (3)\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 6428, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "C:\favanek\main.py", line 94, in callback_inline
    bot.send_message(message.chat.id, '¬озвращайтесь, как передумаете ;)')
AttributeError: 'CallbackQuery' object has no attribute 'chat'

2023-04-13 17:36:07,012 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:36:10,026 DEBUG urllib3.connectionpool Starting new HTTPS connection (1): api.telegram.org:443
2023-04-13 17:36:10,311 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 409 143
2023-04-13 17:36:30,312 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:36:50,396 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:37:10,489 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:37:33,229 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:37:53,312 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:38:15,395 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:38:35,488 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:38:55,576 DEBUG urllib3.connectionpool https://api.telegram.org:443 "GET /bot6234331500:AAG2Hcuep4y4N58uuJeXrHnjbpaSyrpXk3c/getUpdates?offset=379040617&timeout=20 HTTP/1.1" 200 23
2023-04-13 17:39:07,610 ERROR TeleBot Infinity polling: polling exited
2023-04-13 17:39:07,611 ERROR TeleBot Break infinity polling
2023-04-13 17:39:07,612 INFO root Bot STOPPED
